name: Bundler Audit
on:
  pull_request:
  push:
    branches: [ $default-branch ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1

    - run: |
        gem install bundle-audit
        bundle-audit update
        bundle-audit check
