name: Yarn Lint
on:
  pull_request_target:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: "install --ignore-engines --ignore-scripts"

      - name: Run Linters
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
