name: Yarn Test
on:
  pull_request_target:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    name: Yarn Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: c-hive/gha-yarn-cache@v2

      - name: Install Yarn Dependencies
        run: "yarn install --ignore-engines --ignore-scripts"

      - name: Run Tests
        run: yarn test
