name: Gnar Rails Rspec
on:
  push:
    branches: [$default-branch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_PASSWORD: password
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            bundler-cache: true

        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'yarn'

        - name: Setup App Dependencies
          shell: bash
          run: bin/setup

        - name: Generate Assets
          shell: bash
          run: bin/rails assets:precompile

        - name: Run tests
          shell: bash
          run: bin/rspec
