name: Pronto
on: [ pull_request ]
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: HeRoMo/pronto-action@v1.35.0
        with:
          github_token: ${{ secrets.GNARBOT_TOKEN }}
          runner: rubocop brakeman rails_best_practices
          formatters: text github_status github_pr_review
