name: Typedoc
on:
  push:
    branches: [ $default-branch ]

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Build Docs
        run: yarn docs

      - run: sudo chown -R $USER:$USER .

      - name: Create PR (if required)
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GNARBOT_TOKEN }}
          add-paths: 'docs/*'
          commit-message: '📄 Updating Docs 📄'
          delete-branch: true
          labels: |
            docs
            automated
          title: 'Updating Docs 📄'
          body: |
            Updating Docs from recent Merge
